#! /bin/sh
# kcminputrc Mouse cursorTheme 'Oxygen_White'
kcminputrc_mouse_cursortheme=oxy-chrome
# kcminputrc Mouse cursorSize ''
kcminputrc_mouse_cursorsize=0
# ksplashrc KSplash Theme Default
ksplashrc_ksplash_theme=joy
# ksplashrc KSplash Engine KSplashX
ksplashrc_ksplash_engine=KSplashX
# kcmfonts General forceFontDPI 0
kcmfonts_general_forcefontdpi=0
# kdeglobals Locale Language '' # trigger requesting languages from KLocale
kdeglobals_locale_language=zh_CN
klocale_languages=zh_CN:en_US
